# Generated by Django 5.1 on 2024-08-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLegal',
            fields=[
                ('contract_legal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID физ. лица')),
                ('legal_login', models.CharField(max_length=25, verbose_name='Логин юр. лица')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование организации')),
                ('type', models.CharField(max_length=25, verbose_name='Тип')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('legal_adress', models.CharField(max_length=60, verbose_name='Адрес юр. лица')),
                ('inn', models.CharField(max_length=15, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='ContractPhys',
            fields=[
                ('contract_phys_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID физ. лица')),
                ('phys_login', models.CharField(max_length=25, verbose_name='Логин')),
                ('second_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('third_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(max_length=15, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('rate_per_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф в руб./кВтч')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_type', models.CharField(choices=[('Физическое', 'Физическое лицо'), ('Юридическое', 'Юридическое лицо')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата показаний')),
                ('kwh_consumed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='кВт использовано')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачео?')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.consumer')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tariff', verbose_name='Тариф')),
            ],
        ),
    ]
